---
# "auto" essaie de detecter un disque libre simple via lsblk.
# Vous pouvez aussi forcer explicitement un device, par exemple /dev/sdb.

storage_device: auto
storage_vg: vg_app
storage_lv: lv_data
storage_lv_size: 100%FREE
storage_fs_type: xfs
storage_mount_path: /srv/appdata
storage_mount_opts: defaults
